// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Managmet.Data;

#nullable disable

namespace StudentManament.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250807073105_inti")]
    partial class inti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("Student_Managmet.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = true,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPresent = false,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmantId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmantId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Name = "Python Basics"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Name = "Cybersecurity Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 2,
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 3,
                            Name = "Data Visualization"
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.Departmant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Dapartmant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "B+",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "A",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "B",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "C+",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "A-",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmantId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmantId");

                    b.HasIndex("StudentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "heba.youssef@example.com",
                            HireDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Heba Youssef"
                        },
                        new
                        {
                            Id = 2,
                            Email = "karim.nabil@example.com",
                            HireDate = new DateTime(2018, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Karim Nabil"
                        },
                        new
                        {
                            Id = 3,
                            Email = "salma.fathy@example.com",
                            HireDate = new DateTime(2019, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Salma Fathy"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ehab.hassan@example.com",
                            HireDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Ehab Hassan"
                        },
                        new
                        {
                            Id = 5,
                            Email = "rasha.emad@example.com",
                            HireDate = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Rasha Emad"
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.OfficeAssignment", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("OfficeAssignments");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            Location = "Room F101"
                        },
                        new
                        {
                            InstructorId = 2,
                            Location = "Room G202"
                        },
                        new
                        {
                            InstructorId = 3,
                            Location = "Room H303"
                        },
                        new
                        {
                            InstructorId = 4,
                            Location = "Room I404"
                        },
                        new
                        {
                            InstructorId = 5,
                            Location = "Room J505"
                        });
                });

            modelBuilder.Entity("Student_Managmet.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DapartmantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DapartmantId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DapartmantId = 1,
                            DataOfBirth = new DateTime(2002, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.khaled@example.com",
                            Name = "Omar Khaled"
                        },
                        new
                        {
                            Id = 2,
                            DapartmantId = 2,
                            DataOfBirth = new DateTime(2003, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila.mahmoud@example.com",
                            Name = "Laila Mahmoud"
                        },
                        new
                        {
                            Id = 3,
                            DapartmantId = 3,
                            DataOfBirth = new DateTime(2001, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled.samir@example.com",
                            Name = "Khaled Samir"
                        },
                        new
                        {
                            Id = 4,
                            DapartmantId = 4,
                            DataOfBirth = new DateTime(2002, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatma.adel@example.com",
                            Name = "Fatma Adel"
                        },
                        new
                        {
                            Id = 5,
                            DapartmantId = 5,
                            DataOfBirth = new DateTime(2000, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mostafa.ahmed@example.com",
                            Name = "Mostafa Ahmed"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("Student_Managmet.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student_Managmet.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Student_Managmet.Models.Attendance", b =>
                {
                    b.HasOne("Student_Managmet.Models.Course", "Course")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student_Managmet.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Student_Managmet.Models.Course", b =>
                {
                    b.HasOne("Student_Managmet.Models.Departmant", null)
                        .WithMany("Courses")
                        .HasForeignKey("DepartmantId");

                    b.HasOne("Student_Managmet.Models.Instructor", null)
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId");
                });

            modelBuilder.Entity("Student_Managmet.Models.Enrollment", b =>
                {
                    b.HasOne("Student_Managmet.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student_Managmet.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Student_Managmet.Models.Instructor", b =>
                {
                    b.HasOne("Student_Managmet.Models.Departmant", null)
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmantId");

                    b.HasOne("Student_Managmet.Models.Student", null)
                        .WithMany("Instructors")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("Student_Managmet.Models.OfficeAssignment", b =>
                {
                    b.HasOne("Student_Managmet.Models.Instructor", "Instructor")
                        .WithOne("OfficeAssignment")
                        .HasForeignKey("Student_Managmet.Models.OfficeAssignment", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Student_Managmet.Models.Student", b =>
                {
                    b.HasOne("Student_Managmet.Models.Departmant", "Dapartmant")
                        .WithMany("Students")
                        .HasForeignKey("DapartmantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dapartmant");
                });

            modelBuilder.Entity("Student_Managmet.Models.Course", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Student_Managmet.Models.Departmant", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Student_Managmet.Models.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("OfficeAssignment");
                });

            modelBuilder.Entity("Student_Managmet.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Instructors");
                });
#pragma warning restore 612, 618
        }
    }
}
